# Generated by Django 6.0.6 on 2026-07-10 07:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('author', models.CharField(default='Rafiki Afrik', max_length=255)),
                ('featured_image', models.ImageField(upload_to='articles/images/')),
                ('excerpt', models.TextField(help_text='Short description for the card.')),
                ('body', models.TextField(help_text='Full article content.')),
                ('reading_time', models.CharField(help_text="e.g., '5 min read'", max_length=50)),
                ('is_featured', models.BooleanField(default=False, help_text='Check to feature on the homepage.')),
                ('published_date', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='content.category')),
            ],
        ),
        migrations.CreateModel(
            name='VideoStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('youtube_url', models.URLField()),
                ('thumbnail', models.ImageField(upload_to='videos/thumbnails/')),
                ('description', models.TextField(help_text='Short description for the card.')),
                ('is_featured', models.BooleanField(default=False, help_text='Check to feature on the homepage.')),
                ('published_date', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='videos', to='content.category')),
            ],
            options={
                'verbose_name_plural': 'Video Stories',
            },
        ),
    ]
