# Generated by Django 6.0.6 on 2026-07-10 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('director', models.CharField(max_length=255)),
                ('release_year', models.CharField(max_length=4)),
                ('poster_image', models.ImageField(upload_to='films/posters/')),
                ('description', models.TextField(help_text='Synopsis of the film.')),
                ('video_url', models.URLField(blank=True, help_text='Link to the full film or trailer.', null=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('published_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
