# Generated by Django 6.0.6 on 2026-07-12 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_newslettersubscriber'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImpactPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('content_type', models.CharField(choices=[('article', 'Article'), ('video', 'Video')], default='article', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('scheduled', 'Scheduled')], default='draft', max_length=20)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('author_name', models.CharField(blank=True, max_length=150, null=True)),
                ('reading_time', models.CharField(blank=True, max_length=50, null=True)),
                ('excerpt', models.TextField(blank=True, null=True)),
                ('body', models.TextField(blank=True, null=True)),
                ('youtube_url', models.URLField(blank=True, max_length=500, null=True)),
                ('video_description', models.TextField(blank=True, null=True)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='impact_pulse/covers/')),
                ('is_featured', models.BooleanField(default=False)),
                ('publish_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
