# Generated by Django 6.0.6 on 2026-07-12 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_impactpost'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImpactPost',
        ),
    ]
