# Generated by Django 6.0.6 on 2026-07-13 12:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_delete_impactpost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='published_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='videostory',
            name='published_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
