# Generated by Django 6.0.6 on 2026-07-13 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_alter_article_published_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_published',
            field=models.BooleanField(default=True, help_text='Toggle to publish or save as draft.'),
        ),
        migrations.AddField(
            model_name='videostory',
            name='is_published',
            field=models.BooleanField(default=True, help_text='Toggle to publish or save as draft.'),
        ),
    ]
