# Generated by Django 6.0.6 on 2026-07-13 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_article_is_published_videostory_is_published'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='excerpt',
        ),
    ]
