# Generated by Django 6.0.6 on 2026-08-26 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_remove_article_excerpt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='director',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
