# Generated by Django 6.0.6 on 2026-08-26 12:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_alter_film_director'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='is_published',
            field=models.BooleanField(default=True, help_text='Toggle to publish or save as draft.'),
        ),
        migrations.AlterField(
            model_name='film',
            name='published_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
