# Generated by Django 6.0.6 on 2026-09-18 23:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0010_film_is_published_alter_film_published_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='PodcastEpisode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('host', models.CharField(default='Rafiki Afrik', max_length=255)),
                ('embed_url', models.URLField(help_text='URL for Spotify, Apple Podcasts, or YouTube embed.')),
                ('cover_image', models.ImageField(upload_to='podcasts/covers/')),
                ('description', models.TextField(help_text='Show notes and episode description.')),
                ('duration', models.CharField(blank=True, help_text="e.g., '45 mins'", max_length=50, null=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=True)),
                ('published_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name_plural': 'Podcast Episodes',
            },
        ),
    ]
