# Generated by Django 6.0.6 on 2026-09-19 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0011_podcastepisode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='podcastepisode',
            name='cover_image',
        ),
    ]
