# Generated by Django 6.0.6 on 2026-09-24 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0012_remove_podcastepisode_cover_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='podcastepisode',
            name='spotify_url',
            field=models.URLField(blank=True, help_text='Optional link to the Spotify episode', max_length=500, null=True),
        ),
    ]
