# Generated by Django 6.0.6 on 2026-09-26 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0013_podcastepisode_spotify_url'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewsletterSubscriber',
        ),
    ]
