# Generated by Django 6.0.6 on 2026-09-26 07:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('country', models.CharField(max_length=100)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('organization', models.CharField(blank=True, max_length=255, null=True)),
                ('is_approved', models.BooleanField(default=False, help_text='Checked when they are approved to join the Friends from Afrika cohort.')),
                ('is_newsletter_subscribed', models.BooleanField(default=True, help_text='Uncheck if they unsubscribe from the newsletter.')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name_plural': 'Subscribers',
                'ordering': ['-date_joined'],
            },
        ),
    ]
