# Generated by Django 6.0.6 on 2026-07-02 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DynamicSpotlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(default='Featured Event', max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='spotlight/')),
                ('short_description', models.TextField()),
                ('button_text', models.CharField(default='Watch Now', max_length=50)),
                ('button_link', models.URLField()),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('podcasts_produced_count', models.IntegerField(default=0)),
                ('films_produced_count', models.IntegerField(default=0)),
                ('articles_published_count', models.IntegerField(default=0)),
                ('conversations_held_count', models.IntegerField(default=0)),
                ('countries_reached_count', models.IntegerField(default=0)),
                ('strategic_partnerships_count', models.IntegerField(default=0)),
                ('about_who_we_are', models.TextField(default='Overview of Rafiki Afrik and its purpose.')),
                ('about_mission', models.TextField(default="The organization's mission statement.")),
                ('about_vision', models.TextField(default="The organization's vision statement.")),
                ('facebook_url', models.URLField(blank=True, null=True)),
                ('twitter_url', models.URLField(blank=True, null=True)),
                ('instagram_url', models.URLField(blank=True, null=True)),
                ('youtube_url', models.URLField(blank=True, null=True)),
                ('contact_email', models.EmailField(default='hello@rafikiafrik.africa', max_length=254)),
            ],
            options={
                'verbose_name_plural': 'Global Site Settings',
            },
        ),
    ]
