# Generated by Django 6.0.6 on 2026-07-03 05:06

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('author', models.CharField(default='Rafiki Afrik Team', max_length=100)),
                ('featured_image', models.ImageField(upload_to='articles/')),
                ('excerpt', models.TextField(help_text='Short summary for the frontend card')),
                ('body', models.TextField(help_text='Full article content')),
                ('read_time', models.IntegerField(default=5, help_text='Estimated reading time in minutes')),
                ('publish_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_featured', models.BooleanField(default=False)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='core.category')),
            ],
        ),
        migrations.CreateModel(
            name='VideoStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('youtube_url', models.URLField(help_text='Direct link to the YouTube video')),
                ('thumbnail', models.ImageField(upload_to='videos/thumbnails/')),
                ('short_description', models.TextField()),
                ('publish_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_featured', models.BooleanField(default=False)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='videos', to='core.category')),
            ],
        ),
    ]
