# Generated by Django 6.0.6 on 2026-07-03 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_category_article_videostory'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(help_text='e.g., Founder, Editor, Contributor', max_length=100)),
                ('bio', models.TextField()),
                ('profile_picture', models.ImageField(upload_to='team/')),
                ('linkedin_url', models.URLField(blank=True, null=True)),
                ('twitter_url', models.URLField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to hide them from the website')),
                ('order', models.IntegerField(default=0, help_text='Lower numbers appear first (e.g., 1 for Founder)')),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
    ]
