# Generated by Django 6.0.6 on 2026-07-08 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_film'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField(help_text='Detailed description of the service or partnership opportunity')),
                ('image', models.ImageField(blank=True, null=True, upload_to='services/')),
                ('inquiry_button_text', models.CharField(default='Inquire Now', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0, help_text='Lower numbers appear first')),
            ],
            options={
                'verbose_name_plural': 'Services',
                'ordering': ['order', 'title'],
            },
        ),
    ]
