# Generated by Django 6.0.6 on 2026-07-14 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_newslettersubscriber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='category',
        ),
        migrations.RemoveField(
            model_name='videostory',
            name='category',
        ),
        migrations.DeleteModel(
            name='Film',
        ),
        migrations.DeleteModel(
            name='NewsletterSubscriber',
        ),
        migrations.DeleteModel(
            name='Article',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='VideoStory',
        ),
    ]
