# Generated by Django 6.0.6 on 2026-09-26 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_article_category_remove_videostory_category_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WaitlistEntry',
        ),
    ]
